version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  redis:
    build:
      context: .
      dockerfile: srv/celery_broker/Dockerfile
    image: redis:3.2-alpine
    ports:
      - 6379:6379

  celery:
    restart: always
    build:
      context: .
      dockerfile: srv/celery/Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && celery -A auth worker -l info"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - db

  celery_beat:
    restart: always
    build:
      context: .
      dockerfile: srv/celerybeat/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: celery -A auth beat -l info
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
